In [40]:
from numpy import  zeros, array, random, sqrt, floor, bitwise_xor
from numpy.random import randint

Kvadraturna amplitudska modulacija (QAM) koristi se za slanje vise bita podataka odjednom. Podaci koji se salju dele se u dva niza, kojima se modeliraju I i Q komponenta signala. Modulacija u obe grane je amplitudska, a amplituda signala na izlazu zavisi od odredjenog broja bita koji se salju. Broj bitova koji se istovremeno salju predstavljen je sa M, a ukupan broj podataka od M bita sa symbol_num. Signal koji se salje moze biti pojacan sa G. U kodu se nasumicno bira M*symbol_num bitova.

In [41]:
symbol_num = 20
M = 8
G = 1

data_input = randint(2, size=M*symbol_num)
data_input

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0])

Vrednosti koje mogu imati komponente I i Q se dobijaju iz formule ispod. Ove vrednosti su pojacane sa G.

In [42]:
a = array(range(int(2**(M/2))))

for i in range(int(2**(M/2))):
    a[i]=G*((-(2**(M/2))+1)+2*i)
a

array([-15, -13, -11,  -9,  -7,  -5,  -3,  -1,   1,   3,   5,   7,   9,
        11,  13,  15])

Ako je, na primer, jedan simbol 0111, a njegov susedni 1000, u slucaju pojave suma bice promenjena sva 4 bita. Da bi se izbegle prevelike greske usled suma, susedni simboli se razlikuju za po jedan bit. U tu svrhu se koristi Grejev kod.

In [43]:
vect = array(range(int(2**(M/2))))
gray_code = bitwise_xor(vect, floor(vect/2).astype(int))
gray_code

array([ 0,  1,  3,  2,  6,  7,  5,  4, 12, 13, 15, 14, 10, 11,  9,  8],
      dtype=int32)

Kod se deli na sekvence od M bita koji se istovremeno salju.

In [44]:
data_input = data_input.reshape((-1,M))
data_input

array([[0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0]])

Prvih M/2 bita odlazi kod I, a drugih M/2 kod Q. Bitovi se predstavljaju Grejevim kodom, i u zavisnosti od simbola za I i Q, podaci se salju u tom regionu.

In [45]:
I = zeros((data_input.shape[0],))
Q = zeros((data_input.shape[0],))
for n in range(int(data_input.shape[1] / 2)):
    I = I + data_input[:,n] * 2 ** (int(data_input.shape[1]/2)-1-n)
for n in range(int(data_input.shape[1]/2),int(data_input.shape[1])):
    Q = Q + data_input[:,n] * 2 ** (int(data_input.shape[1])-1-n)

I = I.astype(int)
Q = Q.astype(int)

I = gray_code[I]
Q = gray_code[Q]
I = a[I]
Q = a[Q]

I = I.astype(float)
Q = Q.astype(float)

S = I + 1j * Q
S

array([-13. -3.j, -15. -5.j,   7. +3.j,  13. -5.j,  15. -9.j,   9.+15.j,
         3. +1.j,  -7.-13.j,  -9. +5.j,  -7.-13.j, -13. +1.j,   3.+13.j,
        13.-11.j,  -7. +9.j, -13. -9.j,  -7.+13.j,  -5. -7.j,  15.+15.j,
         5. +7.j, -15. +9.j])

Tokom slanja podataka moze doci do pojave suma tako da podaci ne budu na istom mestu kada stignu na odrediste. Ponekad se mogu naci i u regionu drugog simbola.

In [46]:
noise = 1.3
In = array(range(len(I)))
Qn = array(range(len(Q)))
In = In.astype(float)
Qn = Qn.astype(float)
for i in range(len(I)):
    In[i] = I[i]+ round(noise*G-2*noise*G* random.rand(),2)
for i in range(len(Q)):
    Qn[i] = Q[i]+ round(noise*G-2*noise*G* random.rand(),2)
    
Sn = In + 1j * Qn
Sn

array([-14.02 -3.54j, -15.99 -4.68j,   6.06 +2.48j,  14.21 -5.29j,
        13.92 -9.02j,   9.2 +15.98j,   4.09 -0.06j,  -7.42-13.09j,
        -8.92 +4.66j,  -5.72-13.42j, -12.02 +1.45j,   3.97+14.29j,
        13.33-10.29j,  -7.99 +8.53j, -13.07 -8.7j ,  -7.67+13.17j,
        -4.63 -7.76j,  16.3 +14.19j,   5.85 +6.26j, -14.72 +8.68j])

Kada podaci stignu na odrediste, odredjuju se simboli kojima su stigli. Postupak je uglavnom precizan ako sum nije prevelik.

In [47]:
Id=I
Qd=Q
amax=int(2**(M/2)-1)
for i in range(len(I)):
    if Id[i]!=a[0] and Qd[i]!=a[amax]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]-2*G-In[i])**2 + (Qd[i]+2*G-Qn[i])**2):
            Id[i]=Id[i]-2*G
            Qd[i]=Qd[i]+2*G
    if Qd[i]!=a[amax]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]-In[i])**2 + (Qd[i]+2*G-Qn[i])**2):
            Id[i]=Id[i]
            Qd[i]=Qd[i]+2*G
    if Id[i]!=a[amax] and Qd[i]!=a[amax]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]+2*G-In[i])**2 + (Qd[i]+2*G-Qn[i])**2):
            Id[i]=Id[i]+2*G
            Qd[i]=Qd[i]+2*G
    if Id[i]!=a[amax]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]+2*G-In[i])**2 + (Qd[i]-Qn[i])**2):
            Id[i]=Id[i]+2*G
            Qd[i]=Qd[i]
    if Id[i]!=a[amax] and Qd[i]!=a[0]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]+2*G-In[i])**2 + (Qd[i]-2*G-Qn[i])**2):
            Id[i]=Id[i]+2*G
            Qd[i]=Qd[i]-2*G
    if Qd[i]!=a[0]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]-In[i])**2 + (Qd[i]-2*G-Qn[i])**2):
            Id[i]=Id[i]
            Qd[i]=Qd[i]-2*G
    if Id[i]!=a[0] and Qd[i]!=a[0]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]-2*G-In[i])**2 + (Qd[i]-2*G-Qn[i])**2):
            Id[i]=Id[i]-2*G
            Qd[i]=Qd[i]-2*G
    if Id[i]!=a[0]:
        if sqrt((Id[i]-In[i])**2 + (Qd[i]-Qn[i])**2) > sqrt((Id[i]-2*G-In[i])**2 + (Qd[i]-Qn[i])**2):
            Id[i]=Id[i]-2*G
            Qd[i]=Qd[i]
Sd=Id + 1j* Qd
Sd

array([-15. -3.j, -15. -5.j,   7. +3.j,  15. -5.j,  13. -9.j,   9.+15.j,
         5. -1.j,  -7.-13.j,  -9. +5.j,  -5.-13.j, -13. +1.j,   3.+15.j,
        13.-11.j,  -7. +9.j, -13. -9.j,  -7.+13.j,  -5. -7.j,  15.+15.j,
         5. +7.j, -15. +9.j])

Simboli se na kraju pretvaraju u Grejev kod, a onda se pristigli bitovi grupisu i dobija se niz slican ulaznom

In [48]:
Id=Id.astype(int)
Qd=Qd.astype(int)
dictnums={}
for i in range(int(2**(M/2))):
    dictnums.update({a[i] : i})
for i in range(len(I)):
    Id[i]=dictnums.get(Id[i])
    Qd[i]=dictnums.get(Qd[i])   
dictbits={}
for i in range(int(2**(M/2))):
    dictbits.update({gray_code[i] : i})
for i in range(len(I)):
    Id[i]=dictbits.get(Id[i])
    Qd[i]=dictbits.get(Qd[i])

data_exit=[]
for i in range(len(Id)):
    e=[]
    x=0
    while x < M/2:
        b= Id[i] % 2
        e.append(b)
        Id[i]=Id[i]/2
        x=x+1
    e.reverse()
    data_exit.extend(e)
    f=[]
    y=0
    while y < M/2:
        c= Qd[i] % 2
        f.append(c)
        Qd[i]=Qd[i]/2
        y=y+1
    f.reverse()
    data_exit.extend(f)
data_exit=array(data_exit)
data_exit

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0])